### ISSUE TITLE
Use common project structure

### ISSUE THREAD

**Issue by JohnKhandygo** [GladkovaEkaterina/TicTacToe#1]
В java проектах принято файлы исходного кода организовать в определнной структуре папок. Описание одного из наиболее распространенных способов организации проекта смотри [здесь](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) или [здесь](https://stackoverflow.com/questions/41638654/java-project-folder-structure-in-intellij-idea). 

Кроме того, в java принято орагнизовывать классы в пакеты. Общепринятые правила именования пакетов см. [здесь](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html). Понятно, что у Вас скорее всего нет никакого сайта. В этом случае можно его придумать или взять название орагнизации, в рамках которой делается проект. Например, `org.spbstu.your_surname`.

Каждый файл исходного кода должен находится в структуре папок, соответствующей названию его пакета. Например, если файл исходного кода озаглавлен директивой `package com.mycompany.myname`, то этот файл должен располагаться по пути `com/mycompany/myname` относительно папки с исходным кодом внутри проекта.

**Comment by JohnKhandygo** [comment]
Внимательной читай ссылки, которые я скинул. Струткура папок не соответствует общепринятой.

**Comment by JohnKhandygo** [comment]
Актуально.

**Comment by JohnKhandygo** [comment]
У Вас почти получилось. Проблема в том, что src/main/java и src/main/test должны быть обычными директориями, внутри которых уже лежат пакеты. 

Для того, чтобы исправить необходимо сделать следующее:
1. В idea перейти по file -> project structure -> modules (ctrl + alt + shift + S)
2. Убрать маркер sources с папки src. Для этого надо просто щелкнуть по кнопке sources (иконка с синей папкой) пока выбрана папка src либо правой кнопкой по src и выбрать sources.
3. Пометить директорию src/main/java как sources.
4. Пометить директорию src/test/java как tests.
5. Нажать кнопку ОК.
6. Во всех файлах исходного кода исправить название пакета на валидное.

**Comment by GladkovaEkaterina** [comment]
Это тоже вроде исправила
