### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by JohnKhandygo** [GladkovaEkaterina/TicTacToe#2]
По условиям первого задания весь разработанный код должен быть покрыт тестами. Для вычисления процента покрытия используйте [Run with Coverage](https://www.jetbrains.com/help/idea/running-with-coverage.html). От Вас, естественно, не требуется покрывать тестами такие методы, как `equals`, `hashCode` и `toString`.

Без тестов я не начну полноценную проверку задания.

**Comment by JohnKhandygo** [comment]
- [x] У Вас в тестах какой-то бред написан. Вы понимаете, что обозначает запись 
  ```
  class A {
    {
      some code
    }
  }
  ```
  ?
- [x] В тесты необходимо добавить сценарии выхода за границы поля и перезапись значений в клетке. 
- [x] Каждый тестовый сценарий начинается с создания нового экземпляра игрового поля. Для того, чтобы убрать это повторение используйте junit аннотацию [`@Before`](https://junit.org/junit4/javadoc/4.12/org/junit/Before.html).

**Comment by GladkovaEkaterina** [comment]
я, вроде, все исправила, но почему-то не получается запушить последниюю версию кода... проверьте, пожалуйста, хотя бы то, что есть сейчас.

**Comment by GladkovaEkaterina** [comment]
и еще хотела узнать, на какую оценку пока что выполнена данная работа?

**Comment by JohnKhandygo** [comment]
У Вас стоит -1 балл за то, что репозиторий был пуст к моменту первой аттестации. Поэтому, при исправлении замечаний, касающихся реализации и тестов, за это задание будет выставлена оценка 3, при закрытии всех замечаний --- 4.

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочками в предыдущих комментариях, актуально.

**Comment by GladkovaEkaterina** [comment]
добавила.

**Comment by JohnKhandygo** [comment]
Ну такое. То, что Вы в одном тестовом сценарии добавили запись значения в клетку с выходом за пределы поля (даже не проверив, что он там вернет), сложно считать полноценным тестом. Но ок, что-то он все-таки покрывает.
