### ISSUE TITLE
Upgrade impl.

### ISSUE THREAD

**Issue by JohnKhandygo** [GladkovaEkaterina/TicTacToe#4]
- [x] В java все, кроме классов и статических полей, принято именовать в [lowerCamelCase](http://wiki.c2.com/?LowerCamelCase).
- [x] Методы `setX`, `setO` и `clearCell` не учитывают выход за границы массива.
- [x] Методы `setX` и `setO` позволяют перезаписать значение в клетке. В рамках игры это вроде как не совсем корректно.
- [x] Если значение поля/переменной не меняется, то при его объявлении стоит использовать модификатор `final`. Это позволяет избежать дурацких ошибок.
- [x] Поля класса принято объявлять в самом начале класса, до всех остальных методов.

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочками в предыдущих комментариях, актуально.

**Comment by GladkovaEkaterina** [comment]
исправила. теперь перезаписать значение нельзя
