### ISSUE TITLE
Task 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [GladkovaEkaterina/TicTacToe#5]
**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**grep**
Вывод на консоль указанного (в аргументе командной строки) текстового файла с фильтрацией:
word задаёт слово для поиска (на консоль выводятся только содержащие его строки)
- -r (regex) вместо слова задаёт регулярное выражение для поиска (на консоль выводятся только строки, содержащие данное выражение)
- -v инвертирует условие фильтрации (выводится только то, что ему НЕ соответствует)
- -i игнорировать регистр слов

Command Line: crep [-v] [-i] [-r] word inputname.txt

Кроме самой программы, следует написать автоматические тесты к ней.

Также необходимо разработать скрипты и/или инструкции сборки и запуска разработанного приложения из командной строки. 

**P.S.** Проверка второго задания начинается не раньше исправления всех замечания к первому заданию. В любом случае напишите в комментариях к этому issue, когда задание будет готово к проверке.

**P.S.S.** Если будете делать это задание в другом репозитории, дайте ссылку в комментариях к этому issue.

**Comment by JohnKhandygo** [comment]
Рекомендуется следующий подход к разработке:
1. Реализовать класс со всей необходимой логикой так, как Вы это делали в предыдущем задании (с покрытием тестами и прочим). Другими словами, забудьте на время, что Ваше приложение должно работать из консоли.
2. Отдельно написать "обертку", которая будет парсить аргументы командной строки (используя библотеку) и вызывать разработанные на первом этапе методы. Скорее всего то, что будет написано на данном этапе даже не потребуется покрывать тестами, поскольку функциональность сторонних библотек обычно не тестируется (либо тестируется в каких-то очень сложных случаях). 

Собственно после готовности первого этапа можно начинать проверку.

**Comment by GladkovaEkaterina** [comment]
https://github.com/GladkovaEkaterina/grep
но там пока ничего нет, у меня не получается почему-то связать новый проект с гитхабом..

**Comment by GladkovaEkaterina** [comment]
я не понимаю, в чем проблема(

**Comment by JohnKhandygo** [comment]
Сейчас там один коммит, но на заготовку ко второму заданию это все равно не катит.

**Comment by GladkovaEkaterina** [comment]
да, это просто попытка запушить хоть что-то. Само задание в процессе

**Comment by GladkovaEkaterina** [comment]
там уже почти неделю лежит задание, посмотрите, пожалуйста

**Comment by GladkovaEkaterina** [comment]
пожалуйста, проверьте

**Comment by JohnKhandygo** [comment]
Не видел предыдущий комментарий. Обязательно посмотрю.

**Comment by JohnKhandygo** [comment]
Описание задания и замечания перенес в соответствующий репозиторий.
